import Link from "next/link";

export default function EmployersPage() {
  return (
    <div style={{ background: '#f8fafc', minHeight: '100vh', color: '#0f172a' }}>
      
      {/* NAV */}
      <nav style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: 'var(--s-4) var(--s-8)', maxWidth: '1200px', margin: '0 auto' }}>
        <Link href="/" style={{ fontSize: '1.25rem', fontWeight: 700, fontFamily: 'var(--font-outfit)', textDecoration: 'none', color: '#0f172a' }}>
          Career<span style={{ color: '#3b82f6' }}>OS</span>
        </Link>
        <div style={{ display: 'flex', gap: 'var(--s-6)', alignItems: 'center' }}>
          <Link href="/employer/verify" style={{ 
            background: '#0f172a', 
            color: 'white', 
            padding: 'var(--s-2) var(--s-4)', 
            borderRadius: 'var(--r-md)',
            fontWeight: 600,
            textDecoration: 'none'
          }}>
            Login / Verify
          </Link>
        </div>
      </nav>

      {/* HERO SECTION */}
      <section style={{ textAlign: 'center', padding: 'var(--s-20) var(--s-4)', maxWidth: '900px', margin: '0 auto' }}>
        <h1 style={{ 
          fontSize: '3.5rem', 
          fontWeight: 800, 
          lineHeight: 1.1, 
          marginBottom: 'var(--s-6)',
          fontFamily: 'var(--font-outfit)'
        }}>
          Hire Verified Juniors. <br/>
          <span style={{ color: '#ef4444' }}>Not Spammers.</span>
        </h1>
        <p style={{ fontSize: '1.25rem', color: '#475569', marginBottom: 'var(--s-10)', lineHeight: 1.6, maxWidth: '600px', margin: '0 auto var(--s-10) auto' }}>
          Stop sifting through hundreds of low-quality applications. CareerOS connects you with motivated students who have verified profiles and tailored resumes.
        </p>
        <div style={{ display: 'flex', gap: 'var(--s-4)', justifyContent: 'center' }}>
          <Link href="/employer/verify" style={{
            background: '#0f172a',
            color: 'white',
            padding: 'var(--s-4) var(--s-8)',
            borderRadius: 'var(--r-md)',
            fontWeight: 700,
            textDecoration: 'none',
            fontSize: '1.1rem',
            boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)'
          }}>
            Verify Your Company
          </Link>
          <a href="mailto:sales@careeros.uz" style={{
            background: 'transparent',
            border: '1px solid #cbd5e1',
            color: '#0f172a',
            padding: 'var(--s-4) var(--s-8)',
            borderRadius: 'var(--r-md)',
            fontWeight: 600,
            textDecoration: 'none',
            fontSize: '1.1rem'
          }}>
            Contact Sales
          </a>
        </div>
      </section>

      {/* VALUE PROPS */}
      <section style={{ background: 'white', padding: 'var(--s-20) var(--s-4)' }}>
         <div style={{ maxWidth: '1000px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 'var(--s-12)' }}>
            <div>
              <h3 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: 'var(--s-3)' }}>✅ Identity Verification</h3>
              <p style={{ color: '#64748b' }}>We require INN/Registration documents from every employer. This builds trust with high-quality students who avoid skeptical platforms.</p>
            </div>
            <div>
              <h3 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: 'var(--s-3)' }}>📄 Standardized CVs</h3>
              <p style={{ color: '#64748b' }}>Every application comes in a standard, easy-to-read layout generated by our AI. No more messy Word docs or photos of resumes.</p>
            </div>
            <div>
              <h3 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: 'var(--s-3)' }}>🎯 Intent-Based Matches</h3>
              <p style={{ color: '#64748b' }}>Our &quot;Tailoring&quot; engine ensures students actually read your JD before applying. Applications include a match score based on skills.</p>
            </div>
         </div>
      </section>

      {/* FOOTER */}
      <footer style={{ background: '#f8fafc', padding: 'var(--s-10) 0', textAlign: 'center', color: '#94a3b8' }}>
        <p>&copy; 2024 CareerOS for Employers.</p>
      </footer>

    </div>
  );
}
